# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fa47f74744bc3196003d3ce4b4b043b3eb019c3284d27d0b1b0358a07ce94ff8ab78f978e004e931ea5eac70f497db0b373537538792232940ed07dd84e59f7

test:
  secret_key_base: c5718b42c7415aefec74983fa475ce9ec9f747ea753fb7708b743c42d1208d4492d385c6dddcf9e7ab306d066513db73b980aeda88e6c441b89d10acc2341bf6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
