# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4489c919d884df8a5b9c19c8f89487e10c118c8fb70dae902fd7e717653a8d22668f69a6f255b56d7f0852406e112fa90d72e470aaaafd0ba604283feab115fd

test:
  secret_key_base: 391cb04926fb4ec6c3572f87805041de3acb978ef1c8e49687142c64c685fcff4d01800370fde33324199b1aea8182106108b8b9ed6c422185ba3878c578ffda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
